site_name: "CS010 SI: Fall 2016"
pages:
    - [index.md, "Home"]
    - [lab01.md, "Lab 1: Input and Output"]
    - [dis02.md, "Discussion 2: Variables and Math"]
    - [lab02.md, "Lab 2: Variables and Math"]
    - [dis03.md, "Discussion 3: Branches and Characters"]

#    - [lab03.md, "Lab Week 3"]
#    - [lab04.md, "Lab Week 4"]
#    - [lab05.md, "Lab Week 5"]
#    - [lab06.md, "Lab Week 6"]
#    - [lab07.md, "Lab Week 7"]
#    - [lab08.md, "Lab Week 8"]
#    - [dis08.md, "Discussion Week 8"]
#    - [lab09.md, "Lab Week 9"]
#    - [lab10.md, "Lab Week 10"]
theme: readthedocs

