site_name: "CS010 SI: Fall 2016"
pages:
    - [index.md, "Home"]
    - [lab01.md, "Lab 1: Input and Output"]
    - [dis02.md, "Discussion 2: Variables and Math"]
    - [lab02.md, "Lab 2: Variables and Math"]
    - [dis03.md, "Discussion 3: Characters and Branches"]
    - [lab03.md, "Lab 3: Characters and Branches"]
    - [dis04.md, "Discussion 4: Strings and Loops"]
    - [lab04.md, "Lab Week 4: Strings and loops"]
    - [dis05.md, "Discussion 5: Nested Loops and Do-While"]
#    - [lab05.md, "Lab Week 5"]
#    - [lab06.md, "Lab Week 6"]
#    - [lab07.md, "Lab Week 7"]
#    - [lab08.md, "Lab Week 8"]
#    - [dis08.md, "Discussion Week 8"]
#    - [lab09.md, "Lab Week 9"]
#    - [lab10.md, "Lab Week 10"]
theme: readthedocs

