site_name: "CS 12 SI Labs: Winter 2015"
pages:
    - [index.md, "Home"]
#    - [lab01.md, "Lab Week 1"]
#    - [lab02.md, "Lab Week 2"]
#    - [lab03.md, "Lab Week 3"]
#    - [lab04.md, "Lab Week 4"]
#    - [lab05.md, "Lab Week 5"]
#    - [lab06.md, "Lab Week 6"]
#    - [lab07.md, "Lab Week 7"]
#    - [lab08.md, "Lab Week 8"]
#    - [dis08.md, "Discussion Week 8"]
#    - [lab09.md, "Lab Week 9"]
#    - [lab10.md, "Lab Week 10"]
theme: readthedocs

